---
- hosts: all    # 代表在所有主机执行
  remote_user: root #以root身份执行
  tasks:
    - name: Check the date on Server #标签名
      command: date #执行的命令
    - name: Check the ip on Server #标签名
      command: ifconfig ens192